# Generated by Django 2.1.4 on 2018-12-16 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_auto_20181216_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=80, verbose_name='item')),
                ('number', models.CharField(max_length=80, verbose_name='item')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=80, unique=True, verbose_name='location')),
            ],
            options={
                'verbose_name': 'Locations',
                'verbose_name_plural': 'Location',
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80, unique=True, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Types',
                'verbose_name_plural': 'Type',
                'ordering': ['type'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.Location'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.Type'),
        ),
    ]
