# Generated by Django 2.1.4 on 2018-12-17 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hw',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=255, verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.CharField(max_length=80, verbose_name='number'),
        ),
    ]
