# Generated by Django 2.1.4 on 2018-12-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181217_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HW'),
        ),
    ]
