# Generated by Django 2.1.4 on 2018-12-16 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20181215_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_work_day'], 'verbose_name': 'Employees', 'verbose_name_plural': 'Employee'},
        ),
    ]
